llm_response_node:
  ros__parameters:
    # API配置
    api_url: "https://dashscope.aliyuncs.com/compatible-mode/v1"
    api_key: "your_api_key"  # 如果需要API密钥，请在这里设置
    model_name: "qwen3-235b-a22b"
    
    # 请求参数
    max_tokens: 16384
    temperature: 0.7
    
    # 超时设置
    timeout: 30 